name: gh release test
on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: gh
        uses: ./.github/actions/gh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}