name: pull-request

on:
  pull_request:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                ref: "new-branch"
            - name: Echo
              run: echo "pull request based workflow"